### ISSUE TITLE
UI Enhancements - Ui component overlap

### ISSUE THREAD

**Issue by denistsoi** [Keysign-Wallet/keysign#10]
**Describe the bug**
The screen attached shows the account token value overlapping the account amount.
It might help adding. some padding or moving the value so the background doesn't clip the account number,

**To Reproduce**
1. Login with keys/account
2. Show main screen

**Expected behavior**
The account value should be shown below the account number

**Screenshots**
 
<img width="324" alt="Screenshot 2021-03-14 at 2 14 24 PM" src="https://user-images.githubusercontent.com/3061779/111059399-327c4100-84d0-11eb-830f-c8a4c9cb25a0.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Brave / Chrome
 - Version: 1.21.76 / Chromium 89

**Additional context**
N/A

**Comment by mrbusysky** [comment]
We are currently in the process of a redesign so we will keep this in mind.
