### ISSUE TITLE
Check balance before sending coins

### ISSUE THREAD

**Issue by Creatinas** [Keysign-Wallet/keysign#32]
**Is your feature request related to a problem? Please describe.**
Tried sending some coins to address without having enough balance, and it stated that "Transfer successful!". Clearly it did not send any.

**Describe the solution you'd like**
Would be nice to have validation before sending with clear validation message.

**Comment by AbhayAysola** [comment]
Hi Creatinas, thanks for pointing out this issue. It's been fixed in [#e2b9504](https://github.com/Keysign-Wallet/keysign/commit/e2b9504500ab99cf40383b41801b8ac0d23591df)
