### ISSUE TITLE
Feature to Allow Apps choose the banks they want to process transactions

### ISSUE THREAD

**Issue by tomijaga** [Keysign-Wallet/keysign#4]
**Is your feature request related to a problem? Please describe.**
I would like my app to send all transactions through a bank of my choosing. 

**Describe the solution you'd like**
Allow the app using keysign to be able to ask the user to switch to a specific bank by having the keysign extension open up and verifying with the user to approve the switch

**Describe alternatives you've considered**
MrSky suggested we could make it so that apps can set their bank in the transactions handshake to the extension
so any transactions done on site would always be set to said bank

**Comment by AbhayAysola** [comment]
I added this feature and updated the docs to reflect it. This update will be in the chrome and mozilla stores soon.
