### ISSUE TITLE
Face ID login in iOS Device

### ISSUE THREAD

**Issue by hydra91** [Keysign-Wallet/Keysign#41]
**Is your feature request related to a problem? Please describe.**
Most financial apps use face id in iPhone for easy access

**Describe the solution you'd like**
integrate login with face id when open in iPhone

**Describe alternatives you've considered**
no alt

**Additional context**

**Comment by mrbusysky** [comment]
Wrong repo for this you are looking for https://github.com/Keysign-Wallet/Keysign-Mobile
