### ISSUE TITLE
[Feature] Add Receive button on accounts page.

### ISSUE THREAD

**Issue by hussu010** [Keysign-Wallet/Keysign#44]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to be able to copy my account number from the home page so that I can send it over to other users without the need to go to the manage wallets page.

**Describe the solution you'd like**
Add a "receive" button alongside the "send" and "history" buttons on the homepage of the application.

**Additional context**
![Capture](https://user-images.githubusercontent.com/55182298/158087675-c1302535-6438-417d-8b7f-4b589ae18543.PNG)

**Comment by mrbusysky** [comment]
Addressed issue in new design for the next update https://www.figma.com/file/RPsbH8sEnIXue8uLir3W9R/Updated-Keysign-Extension?node-id=33%3A112
