### ISSUE TITLE
Password creation text cutoff

### ISSUE THREAD

**Issue by wendtl** [Keysign-Wallet/keysign#6]
**Describe the bug**
While setting up the extension, the password help text appears to be cut off

**To Reproduce**
1. Install the extension
2. Attempt to create a password that does not meet the requirements

**Screenshots**
![keysign-text-cutoff](https://user-images.githubusercontent.com/10553159/104112141-b471a300-52b0-11eb-97ec-d32d53b29d91.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.x

**Comment by AbhayAysola** [comment]
Fixed in commit
